version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    target-branch: staging
    labels:
      - dependencies
      - npm

  - package-ecosystem: pip
    directory: "/apps/api"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    target-branch: staging
    labels:
      - dependencies
      - python

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    target-branch: staging
    labels:
      - dependencies
      - github-actions

  - package-ecosystem: docker
    directory: "/apps/api"
    schedule:
      interval: weekly
      day: monday
    target-branch: staging
    labels:
      - dependencies
      - docker

  - package-ecosystem: docker
    directory: "/apps/web"
    schedule:
      interval: weekly
      day: monday
    target-branch: staging
    labels:
      - dependencies
      - docker
